export type { Blob, BlobParams } from './blob.js';
export { generateBlob } from './blob.js';
export { dropSmallComponents } from './components.js';
export { dilate, erode, morphologicalOpen } from './morphology.js';
export { fillHoles } from './holes.js';
export type { RepairOptions } from './repair.js';
export { MaskRepairError } from './errors.js';
export { assertBlockAligned, repairMask } from './repair.js';
export { absorbParity } from './parity.js';
export type { MaskGeometry, RegionLabels } from './regions.js';
export { labelRegions, maskFrom, regionSizes, regionSubMask } from './regions.js';
