/**
 * Bakes the approved library into the files the app ships: one packed bitmap
 * asset, a manifest naming the shapes in it, and the third-party notice, all
 * from a pinned upstream version so a clean checkout reproduces them byte for
 * byte.
 *
 * Usage: npm run shapes [-- --check] [-- --verify] [-- --tarball <path>]
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import { generateBoard } from '../../src/core/generate.js';
import {
  SHAPE_ASSET_FILE,
  SHAPE_ASSET_VERSION,
  SHAPE_MANIFEST_FILE,
  encodeShapeAsset,
  type ShapeManifest,
} from '../../src/game/shapeLibrary.js';
import { genParamsForShape, shapeGenerateOptions } from '../../src/game/shapeBoard.js';
import type { ShapeSummary } from '../../src/game/shapes.js';
import { BAKE_EDGE, bakeInk } from './bake.js';
import { openPhosphor, PHOSPHOR_PACKAGE, PHOSPHOR_VERSION } from './phosphor.js';
import { openRasteriser } from './raster.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const APPROVED = join(ROOT, 'docs', 'shapes', 'approved.json');
const PUBLIC = join(ROOT, 'public');
const NOTICES_FILE = 'THIRD-PARTY-NOTICES.md';

function flag(name: string): boolean {
  return process.argv.includes(name);
}

function option(name: string): string | undefined {
  const at = process.argv.indexOf(name);
  return at === -1 ? undefined : process.argv[at + 1];
}

function readApproved(): ShapeSummary[] {
  const parsed: unknown = JSON.parse(readFileSync(APPROVED, 'utf8'));
  if (!Array.isArray(parsed)) throw new Error(`${APPROVED} is not an array`);
  return parsed.map((entry: unknown, at: number): ShapeSummary => {
    const { id, name } = entry as Partial<ShapeSummary>;
    if (typeof id !== 'string' || typeof name !== 'string') {
      throw new Error(`approved.json entry ${at} has no id and name`);
    }
    return { id, name };
  });
}

function manifestText(shapes: readonly ShapeSummary[]): string {
  const manifest: ShapeManifest = {
    version: SHAPE_ASSET_VERSION,
    edge: BAKE_EDGE,
    source: `${PHOSPHOR_PACKAGE}@${PHOSPHOR_VERSION}`,
    shapes: shapes.map((shape, index) => ({ ...shape, index })),
  };
  const entries = manifest.shapes.map((shape) => `    ${JSON.stringify(shape)}`).join(',\n');
  return (
    `{\n  "version": ${manifest.version},\n  "edge": ${manifest.edge},\n` +
    `  "source": ${JSON.stringify(manifest.source)},\n  "shapes": [\n${entries}\n  ]\n}\n`
  );
}

function noticesText(license: string): string {
  return (
    '# Third-party notices\n\n' +
    'Generated by the shape bake from the licence file it fetches, so the notice\n' +
    'cannot drift from the version actually shipped. Edit the bake, not this file.\n\n' +
    `## Phosphor Icons — ${PHOSPHOR_PACKAGE} ${PHOSPHOR_VERSION}\n\n` +
    'The shape library is rasterised from this set at build time. No upstream art\n' +
    'is redistributed; each shape ships as a bitmap derived from it.\n\n' +
    `\`\`\`\n${license.trimEnd()}\n\`\`\`\n`
  );
}

interface Output {
  readonly path: string;
  readonly bytes: Uint8Array;
}

function report(outputs: readonly Output[], shapeCount: number): void {
  for (const { path, bytes } of outputs) {
    const gzipped = gzipSync(bytes).length;
    process.stdout.write(
      `${path.slice(ROOT.length + 1).padEnd(28)} ${String(bytes.length).padStart(7)} B  ` +
        `${String(gzipped).padStart(7)} B gzipped\n`,
    );
  }
  process.stdout.write(`${shapeCount} shapes at ${BAKE_EDGE}x${BAKE_EDGE}\n`);
}

/**
 * Rebuilds every board the app would open on. Slow enough to be opt-in, and
 * the only check that the shipped seed — not the one curation judged at —
 * still produces a board for every shape.
 */
function verifyBoards(shapes: readonly ShapeSummary[], inks: readonly Uint8Array[]): void {
  const failures: string[] = [];
  shapes.forEach((shape, at) => {
    const params = genParamsForShape(shape.id);
    try {
      const drawing = { ink: inks[at] as Uint8Array, edge: BAKE_EDGE };
      generateBoard(params, shapeGenerateOptions(drawing, params.gridSize));
    } catch (cause) {
      failures.push(`${shape.id}: ${(cause as Error).message.slice(0, 120)}`);
    }
  });
  process.stdout.write(`${shapes.length - failures.length}/${shapes.length} shapes generate\n`);
  for (const failure of failures) process.stdout.write(`  ${failure}\n`);
  if (failures.length > 0) process.exitCode = 1;
}

async function main(): Promise<void> {
  const shapes = readApproved();
  const phosphor = await openPhosphor(option('--tarball'));
  const raster = await openRasteriser();
  const inks: Uint8Array[] = [];
  for (const shape of shapes) {
    const svg = phosphor.icon(shape.id);
    if (svg === null) {
      throw new Error(`${PHOSPHOR_PACKAGE}@${PHOSPHOR_VERSION} has no icon "${shape.id}"`);
    }
    inks.push(await bakeInk(raster, svg));
  }
  await raster.close();

  const encoder = new TextEncoder();
  const outputs: Output[] = [
    { path: join(PUBLIC, SHAPE_ASSET_FILE), bytes: encodeShapeAsset(BAKE_EDGE, inks) },
    { path: join(PUBLIC, SHAPE_MANIFEST_FILE), bytes: encoder.encode(manifestText(shapes)) },
    { path: join(PUBLIC, NOTICES_FILE), bytes: encoder.encode(noticesText(phosphor.license)) },
    { path: join(ROOT, NOTICES_FILE), bytes: encoder.encode(noticesText(phosphor.license)) },
  ];

  if (flag('--verify')) verifyBoards(shapes, inks);

  if (flag('--check')) {
    const stale = outputs.filter(({ path, bytes }) => !sameAsOnDisk(path, bytes));
    report(outputs, shapes.length);
    if (stale.length === 0) {
      process.stdout.write('every baked file matches what is committed\n');
      return;
    }
    for (const { path } of stale) process.stderr.write(`stale: ${path.slice(ROOT.length + 1)}\n`);
    process.exitCode = 1;
    return;
  }

  for (const { path, bytes } of outputs) writeFileSync(path, bytes);
  report(outputs, shapes.length);
}

function sameAsOnDisk(path: string, bytes: Uint8Array): boolean {
  try {
    return Buffer.from(bytes).equals(readFileSync(path));
  } catch {
    return false;
  }
}

await main();
